### ISSUE TITLE
Easing tween implementation?

### ISSUE THREAD

**Issue by shibekin69** [loudoweb/SpriterHaxeEngine#19]
Hi! While playing around with a test animation, I noticed that the the easing tween between frames in Spriter aren't working/implemented yet. Animation tweens only play in a linear way.

**Comment by loudoweb** [comment]
Hi, non linear tween should work since the following commit https://github.com/loudoweb/SpriterHaxeEngine/commit/f67d62e77165da7132682d476c7b0fe82b6a0d3e

So, can you try again with last version and provide a sample for debugging if it's not working? Thanks.

Note that you can find samples with custom curves test working here : https://github.com/loudoweb/Spriter-Example

**Comment by shibekin69** [comment]
Ah thanks! I hope I remember this. I'll try and get back to this when I get back to coding :)
