### ISSUE TITLE
Flip Animation

### ISSUE THREAD

**Issue by Tembac** [loudoweb/SpriterHaxeEngine#23]
Hello,

I'm trying to implement spriter with HaxeFlixel using SpriterHaxeEngine.
The problem I encountered is that I can't flip the spriter sprites.

I tried this:

if (flipX)
					{
						//spriterAnims.info.scaleX = -1;
						spriterAnims.info.scaleY = -1;
					}
					else
					{
						//spriterAnims.info.scaleX = 1;
						spriterAnims.info.scaleY = 1;
					}

But id does crazy things. Is there any solution?

**Comment by loudoweb** [comment]
It seems that it's a missing feature.
I also need this feature so I will probably write it, but not before October because I don't have the time right now.

A temporary fix exists within Spriter by creating a clone of your animation:
-select your animation in the animation pannel
-click on the ... button
-create a clone with scaleX -1 or scaleY -1

**Comment by loudoweb** [comment]
Maybe it's a bug because I see that some other implementations have the same behavior. I guess there is an error in the scml reference. See http://brashmonkey.com/forum/index.php?/topic/3127-flipping-not-working/?hl=flip

**Comment by sruloart** [comment]
Shouldn't you be doing the flipping part with Flixel? .info.scaleX is only relevant when you first create the FlxSprites (AFAIK). On dev there are a number of options, I'm not too sure what you should use on 3.3.11 but I think there's a related FlxAtlas demo for that (just don't mistake the dev version to be the 3.3.11 compatible version, that won't work).

**Comment by loudoweb** [comment]
Finally I made the change because I was able to find a fix in the Spriter forum :)
So 2 solutions for you right now : grab the dev branch of this repo (beware that I didn't test this branch with Flixel right now so please give me feedback), or just update the SpriterHaxeEngine with the updated file or line.

**Comment by loudoweb** [comment]
What do you mean @sruloart ? the dev branch of SpriterHaxeEngine is not working with Flixel?

Can somebody provide me a quick sample project using Flixel and SpriterHaxeEngine, I will be able to test myself on flixel that way :)

**Comment by sruloart** [comment]
Master should work with master (`spatialResult` in the FlixelLibrary) dev with dev (`info` in the FlixelLibrary). I'm working with dev and a demo is a good idea, HaxeFlixel would benefit from that as well, so I would definitely look into it. 

What I've meant to say is that you don't have to use the engine to tell you something is flipped, you can just flip it using Flixel directly (both on master and on dev). 

Using the angle to flip the sprite? wouldn't it just spin it around?

**Comment by loudoweb** [comment]
> Using the angle to flip the sprite? wouldn't it just spin it around?

I'm just following the fix I saw on Spriter forum. I'm not sure of how to do that otherwise right now.
