### ISSUE TITLE
Some bone animations explode

### ISSUE THREAD

**Issue by Tembac** [loudoweb/SpriterHaxeEngine#24]
I think this is derived from bug #23 

I made a demo with a stripped version of the platformer I'm making to test the animations using HaxeFlixel and the demo animations from spriter:

https://dl.dropboxusercontent.com/u/24695185/HaxeFlixelSpriterTest.rar

Some of the animations "explode" when are playing.

For the project I'm using the latest dev flixel and SpriterHaxeEngine. Notice that I added _dev to the names of the libraries.

@sruloart, maybe we can use this demo for HaxeFlixel when the issues are fixed?

**Comment by sruloart** [comment]
Are you sure it's working because this line in the playstate is a little broken (null and lib should be vice-versa):
```haxe
engine = new SpriterEngine(Assets.getText("assets/images/GreyGuy/player.scml"), null, lib);
```
Also, for the actual demo I think something as simple as a character displayed on screen (+animations and so on), this is just a bit too much. Also, I would use the FlxAtlasFrames to save up draw calls, there are a gazillion objects apparently :)

**Comment by sruloart** [comment]
OK, so I was on the wrong branch for some reason, but now I can confirm that both master and dev work with the dev branch of HaxeFlixel, hooray!

Now, for the (very) recent fix with the angles - it does work, but it breaks the animations which are playing. I would bet this angle solution is missing from another class where it's necessary.

**Comment by sruloart** [comment]
And it can be that (FlixelLibrary): 
```haxe
sprite.angle = SpriterUtil.fixRotation(info.angle);
```
So maybe `fixRotation`...

**Comment by loudoweb** [comment]
Hello,

I have tested your project. Indeed the walk animation and some others are not working.
So I tested before the last fix and it seems to no work too. So this is not a regression bug from the last fix.
I've tested on my sample project and I have the very same problem no matter what kind of library I use, so this is not a FlixelLibrary problem.
Then I have tested on the SpriterHaxeEngine version 1.6.0/master branch (from haxelib) and it works better. Why I'm saying better? Because I've tested all the animation on your scml, and only the stand_up animation is not working but all the others are working. So this is better than the dev branch but not perfect.

Conclusion : 
There is a regression bug in the dev branch (the improved version 2 I'm trying to build)
It seems that the bone support was not perfect anyway.
My guess is that the problem comes from the bone calculation (probably from the parent bone).

For now I don't have the time to look deeper in it in the coming weeks :(

**Comment by Tembac** [comment]
I think I will make the animations using spriter but export them to sprite sheets for my current game. I hope you can fix this in the future. 

Is there any plan to fix this?
Can you point me to what is broken to see If I can fix it? 

Thanks!

**Comment by loudoweb** [comment]
Hello,

I would like to fix it, but I do not know when I will have the time.

I think the problem is in the bone calculation (probably from the parent bone) and it probably came with a recent change in the dev branch :(

So a good idea will be to test different commits since the dev branch up exists to see what change is buggy.

The calculation is located here : 
https://github.com/loudoweb/SpriterHaxeEngine/blob/dev/spriter/definitions/SpriterAnimation.hx#L126-L168

Also, we should definitely look closer to the unmapFromParent method if there is something wrong.

Hope this helps. I will come back here as soon as I will have the time to work on it. Thanks.

**Comment by loudoweb** [comment]
I think I found the problem. I'm reusing SpatialInfo object the wrong way so it overrides some data. I'll try to fix this this week. Cheers.

**Comment by Tembac** [comment]
Thanks! 
Let me know if you need something more to test. 

A different bug I found, that I don't know if I should report separate, is that i can't use several entities on the same file. 
I have different entities with different animations on the same scml file. I add them using the following code on different sprites: 

private var spriterAnims:Spriter;

spriterAnims = PlayState.instance.engine.addEntity("Bombas", X, Y);
spriterAnims.playAnim("bomba_Idle");

But only the first entity added is shown for every sprite.

**Comment by loudoweb** [comment]
Strange. Because if you don't specify the ScmlObject in the addEntity method, the default scml is cloned so you should have differents sprites.

I'm not able to reproduce the bug, can you send me a test file?

Just for information:
For now the engine use some data on the scml to work (time, currentEntity, map...)
Other user reports that this data should be embedded in Spriter.hx and not SCMLObject.hx to avoid creating multiple ScmlObject.

**Comment by Tembac** [comment]
Thanks, I will make a test file. The things I'm working now have copyrigth I will see to make an example that changes that.

**Comment by Tembac** [comment]
I made a test based on my project. The important classes for this test are Player and PlayerBombs

If you press X the player will shoot playerBombs. They should be two entities but they show the same graphic. 

https://dl.dropboxusercontent.com/u/24695185/HaxeFlixelSpriterTest.rar

**Comment by loudoweb** [comment]
There is a confusion in your code. There is a difference between the physical entity in your screen and the entity name in Spriter software. If you want 3 bombs in your screen you are using the same entity from the scml but you should set an unique name when creating a Spriter object. It allows to retrieve a specific object using the SpriterEngine.getEntity method. Maybe I should rename the method to avoid confusion. **For example, something like : addSpriter and getSpriter ???**

You are not using the correct entity.
Please try this instead : 
```haxe
spriterAnims = PlayState.instance.engine.addEntity("Bombas_"+X+"_"+Y, X, Y);
spriterAnims.playAnimFromEntity("Bombas","bomba_Idle");
```

**Comment by Tembac** [comment]
Thanks! Sorry for my delay. 

I think it is confusing. What does "Bombas_"+X+"_"+Y mean?

**Comment by loudoweb** [comment]
Ok I will change the name of the method to avoid confusion.

I just put this as an example to use an unique name for the bombas (but it's not really an unique name because you can throw many bombas at the same position :) )

**Comment by Tembac** [comment]
Ahh, I get it now. Thanks for the help :D

Let me know if you need help testing more things.

**Comment by loudoweb** [comment]
I find the last bug remaining on Bones. It seems that the engine interpolates only the custom pivot and not those set in the files.

**Comment by Tembac** [comment]
Great! The project I was using to test is very outdated but I found a related bug on a new game I'm making. I can't send you the scml but basically if I delete the pivot of the part where is getting crazy it seem to work fine:

Original:
(This is line 8916 on a file with several animations)
```
            <timeline id="13" name="capaBack01A">
                <key id="0" spin="0">
                    <object folder="4" file="0" x="32.31553" y="2.29003" pivot_x="0.5" pivot_y="0.5" angle="269.772637"/>
                </key>
                <key id="1" time="361" spin="0">
                    <object folder="4" file="3" x="32.31553" y="2.29003" angle="269.772637"/>
                </key>
                <key id="2" time="1298" spin="0">
                    <object folder="4" file="3" x="33.153655" y="3.197679" pivot_x="0.5" pivot_y="0.5" angle="269.772637"/>
                </key>
            </timeline>
```

Fixed:
```
            <timeline id="13" name="capaBack01A">
                <key id="0" spin="0">
                    <object folder="4" file="0" x="32.31553" y="2.29003" angle="269.772637"/>
                </key>
                <key id="1" time="361" spin="0">
                    <object folder="4" file="3" x="32.31553" y="2.29003" angle="269.772637"/>
                </key>
                <key id="2" time="1298" spin="0">
                    <object folder="4" file="3" x="33.153655" y="3.197679" pivot_x="0.5" pivot_y="0.5" angle="269.772637"/>
                </key>
            </timeline>
```

**Comment by loudoweb** [comment]
So basically, for now, if you want to have interpolation on pivot, it works only if they are all set in <object>. If you don't want interpolation on pivot, you should remove pivot from <object> and use default pivot instead.

I will update the library soon with a fix and some faster code :)

**Comment by Tembac** [comment]
Great work @loudoweb !
