### ISSUE TITLE
Compatibility problem with haxe 3.4.0

### ISSUE THREAD

**Issue by Tembac** [loudoweb/SpriterHaxeEngine#37]
The following error is not letting me compile using the latest Haxe:

C:/HaxeToolkit/haxe/lib/SpriterHaxeEngine/2,0,0/spriter/definitions/Metaline.hx:9: characters 9-38 : Warning : Structures with new are deprecated, use haxe.Constraints.Constructible instead

**Comment by loudoweb** [comment]
Thanks for the report.

Do you have any proposal? I think we could just remove the Type Parameter...

**Comment by Tembac** [comment]
I don't know. The Docs about it on haxe are not updated yet.

**Comment by frankhdz** [comment]
The new method is supposed to be defined like this:
```
typedef ConstructibleKey = {
  public static var fast:Fast;
}
```
But this is creating other problems in other parts of the code

**Comment by loudoweb** [comment]
Thanks for your suggestion. What other problems are you talking about?

**Comment by loudoweb** [comment]
Maybe we could just replace 
`class Metaline<T:ConstructibleKey>`
by
`class Metaline<T>`
Can you test?

**Comment by frankhdz** [comment]
Well it seems I got passed the constructible error but now there is an error with the tile layer lib. It is not compatible with openfl 4. It is calling a deprecated method:
```
openfl.display.Tilesheet

haxe/lib/tilelayer/0,2,0/aze/display/TileSprite.hx:175: characters 27-42 : aze.display.TileLayer has no field tilesheet
```

**Comment by loudoweb** [comment]
Are you using SpriterHaxeEngine from git or haxelib?
On git I've made a [Tilemap library](https://github.com/loudoweb/SpriterHaxeEngine/blob/dev/spriter/library/TilemapLibrary.hx) on the [dev branch](https://github.com/loudoweb/SpriterHaxeEngine/tree/dev) and have forgot to release it on master branch and haxelib. Can you try?
If it works I'll update SpriterHaxeEngine this weekend with a fix for haxe 3.4 and openfl 4.
Thanks.

**Comment by frankhdz** [comment]
Using the one from haxelib.

I will give the Git version hopefully later today and give you some feed back.

**Comment by frankhdz** [comment]
I tested with the Git version and still getting a tilemap but on a different line. This is still related to the deprecated openfl.display.Tilesheet. The guys over at openfl say we should be using openfl.display.Tilemap. Unfortunately the tilelayer lib seems to be abandoned with not activity since 2013. 

/usr/local/lib/haxe/lib/tilelayer/0,2,0/aze/display/TilesheetEx.hx:4: characters 7-31 : Type not found : openfl.display.Tilesheet

**Comment by Tembac** [comment]
Haxeflixel is not compatible with openfl 4 yet. I think that I'll have to keep using older version of haxe and this library.

**Comment by loudoweb** [comment]
@frankhdz are you using flixel?
If not, the dev branch of SpriterHaxeEngine has a TilemapLibrary. I'll merge into the master branch this weekend after some tests to check if everything works correctly. But it would be great if someone else makes also some tests.

**Comment by frankhdz** [comment]
No, not using Flixel, I am trying to implement it with Starling.

**Comment by loudoweb** [comment]
Sorry for the long wait. I've fixed the issue.

@frankhdz To make it working you can use [TilemapLibrary ](https://github.com/loudoweb/SpriterHaxeEngine/blob/master/spriter/library/TilemapLibrary.hx)or create your own StarlingLibrary. You can import your atlas with [openfl-atlas](https://github.com/loudoweb/openfl-atlas) instead of using a deprecated library as Tilelayer.
