### ISSUE TITLE
openfl & haxeflixel examples

### ISSUE THREAD

**Issue by nykevinwong** [loudoweb/SpriterHaxeEngine#39]
can we have haxeflixel source code examples of running simple Spriter bone animation?

**Comment by loudoweb** [comment]
Is this enough?

https://github.com/loudoweb/SpriterHaxeEngine/blob/master/spriter/library/FlixelLibrary.hx#L31-L56

**Comment by Aboideau** [comment]
> 
> 
> Is this enough?
> 
> https://github.com/loudoweb/SpriterHaxeEngine/blob/master/spriter/library/FlixelLibrary.hx#L31-L56

Am I correct to assume that in that highlighted comment instead of `engine.addEntity()` it should be `engine.addSpriter()`?

I spent quite some time figuring out how to make this work because I'm a dumdum. So here's what worked for me.

### A basic example
Create a new project (if you need to) with `flixel tpl -n "TypeInYourProjectNameHere"`. In the default project folder layout you'll find the `source` folder with the `PlayState.hx` file in it. There you can paste the code from bellow (or from this [gist](https://gist.github.com/Aboideau/2d4e56e83fc965b1ed6f44bd4583ca0e)).
```
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.group.FlxGroup;
import openfl.Assets;
import spriter.engine.SpriterEngine;
import spriter.library.FlixelLibrary;

class PlayState extends FlxState
{
	var engine:SpriterEngine;

	override public function create()
	{
		var spriterGroup:FlxTypedGroup<FlxSprite> = new FlxTypedGroup<FlxSprite>();
		var lib:FlixelLibrary = new FlixelLibrary(spriterGroup, 'assets/images/WonkySkeleton/');
		engine = new SpriterEngine(Assets.getText('assets/images/WonkySkeleton/WonkySkeleton.scml'), lib, null);
		engine.addSpriter('WonkySkeleton', 300, 300);
		add(spriterGroup);
	}

	override public function update(elapsed:Float)
	{
		super.update(elapsed);
		engine.update(Std.int(1000 * elapsed));
	}
}
```

Don't forget to add your animated Spriter Pro project into the `assets` folder and rename the _WonkySkeleton_ that I used in the code to the one that you have. Then run it with `lime test html5`.

**Comment by loudoweb** [comment]
- [ ] TODO Fix the comment in the FlixelLibrary

thanks @Aboideau I'll do it when I'll have time
